require 'busted.runner'()

local factorial = require('factorial')

describe("factorial tests with busted framework", function()
    it("factorial imperative implementation", function()
        assert.are.equal(factorial.fact_imp(0), 1)
        assert.are.equal(factorial.fact_imp(1), 1)
        assert.are.equal(factorial.fact_imp(5), 120)
    end)
    it("factorial recursive implementation", function()
        assert.are.equal(factorial.fact_rec(0), 1)
        assert.are.equal(factorial.fact_rec(1), 1)
        assert.are.equal(factorial.fact_rec(5), 120)
    end)
    it("equality between different factorial implementation", function()
        assert.are.equal(factorial.fact_imp(10), factorial.fact_rec(10))
    end)
    it("check raising errors", function()
        assert.has.errors(function() factorial.fact_imp(-42) end)
        assert.has.errors(function() factorial.fact_rec(-42) end)
    end)
end)
