require "busted.runner" ()

local linked_list = require("linked_list")

describe("linked_list tests with busted framework", function ()
    it("create :: push :: size", function ()
        local ll = linked_list.create()
        assert.are.equal(0, linked_list.size(ll))
        ll = linked_list.push(84, ll)
        assert.are.equal(1, linked_list.size(ll))
        ll = linked_list.push(42, ll)
        assert.are.equal(2, linked_list.size(ll))
        ll = linked_list.push(21, ll)
        assert.are.equal(3, linked_list.size(ll))
    end)
    it("create :: pop :: size", function ()
        local ll = linked_list.create()
        ll = linked_list.push(168, ll)
        ll = linked_list.push(84, ll)
        ll = linked_list.push(42, ll)
        ll = linked_list.push(21, ll)
        assert.are.equal(4, linked_list.size(ll))

        local pop_value
        ll, pop_value = linked_list.pop(ll)
        assert.are.equal(21, pop_value)
        assert.are.equal(3, linked_list.size(ll))
        ll, pop_value = linked_list.pop(ll)
        assert.are.equal(42, pop_value)
        assert.are.equal(2, linked_list.size(ll))
        ll, pop_value = linked_list.pop(ll)
        assert.are.equal(84, pop_value)
        assert.are.equal(1, linked_list.size(ll))
    end)
end)
